In [1]:
import pandas as pd
import numpy as np

In [2]:
data=pd.read_csv("ICRISAT-District Level Data.csv")

In [3]:
data

,Dist Code,Year,State Code,State Name,Dist Name,RICE AREA (1000 ha),RICE PRODUCTION (1000 tons),RICE YIELD (Kg per ha),WHEAT AREA (1000 ha),WHEAT PRODUCTION (1000 tons),...,SUGARCANE YIELD (Kg per ha),COTTON AREA (1000 ha),COTTON PRODUCTION (1000 tons),COTTON YIELD (Kg per ha),FRUITS AREA (1000 ha),VEGETABLES AREA (1000 ha),FRUITS AND VEGETABLES AREA (1000 ha),POTATOES AREA (1000 ha),ONION AREA (1000 ha),FODDER AREA (1000 ha)
0,1,1966,14,Chhattisgarh,Durg,548.00,185.00,337.59,44.00,20.00,...,1777.78,0.0,0.0,0.0,5.95,6.64,12.59,0.01,0.20,0.47
1,1,1967,14,Chhattisgarh,Durg,547.00,409.00,747.71,50.00,26.00,...,1500.00,0.0,0.0,0.0,5.77,7.24,13.02,0.01,0.30,1.23
2,1,1968,14,Chhattisgarh,Durg,556.30,468.00,841.27,53.70,30.00,...,1000.00,0.0,0.0,0.0,5.41,7.40,12.81,0.10,0.50,1.02
3,1,1969,14,Chhattisgarh,Durg,563.40,400.80,711.40,49.40,26.50,...,1900.00,0.0,0.0,0.0,5.52,7.16,12.69,0.01,0.40,0.84
4,1,1970,14,Chhattisgarh,Durg,571.60,473.60,828.55,44.20,29.00,...,2000.00,0.0,0.0,0.0,5.45,7.19,12.64,0.02,0.40,0.42
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
16141,917,2013,15,Jharkhand,Singhbhum,267.06,579.70,2170.67,1.53,1.85,...,0.00,0.0,0.0,0.0,0.00,9.02,9.03,0.48,1.58,0.00
16142,917,2014,15,Jharkhand,Singhbhum,256.33,586.63,2288.57,5.36,6.65,...,0.00,0.0,0.0,0.0,0.00,8.63,8.64,0.46,0.84,0.00
16143,917,2015,15,Jharkhand,Singhbhum,263.21,264.71,1005.70,1.99,1.82,...,0.00,0.0,0.0,0.0,0.00,6.84,6.85,0.42,0.95,0.00
16144,917,2016,15,Jharkhand,Singhbhum,224.05,319.01,1423.84,0.38,0.83,...,0.00,0.0,0.0,0.0,0.03,6.40,6.43,0.03,0.11,0.00
16145,917,2017,15,Jharkhand,Singhbhum,386.91,669.97,1731.62,0.00,0.00,...,0.00,0.0,0.0,0.0,0.00,0.00,0.00,0.00,33.33,0.00

In [4]:
#Data cleaning

#Filling the null values
outlier_columns = ['RICE YIELD (Kg per ha)','WHEAT YIELD (Kg per ha)','KHARIF SORGHUM YIELD (Kg per ha)','SORGHUM YIELD (Kg per ha)','PEARL MILLET YIELD (Kg per ha)','MAIZE YIELD (Kg per ha)','FINGER MILLET YIELD (Kg per ha)']
for col in outlier_columns:
      data[col]=data[col].fillna(data[col].median())


#Cleaning outliers
cols = ['Dist Code','RICE AREA (1000 ha)', 'RICE PRODUCTION (1000 tons)','RICE YIELD (Kg per ha)','WHEAT AREA (1000 ha)','WHEAT PRODUCTION (1000 tons)','WHEAT YIELD (Kg per ha)','KHARIF SORGHUM AREA (1000 ha)', 'KHARIF SORGHUM PRODUCTION (1000 tons)','KHARIF SORGHUM YIELD (Kg per ha)','SORGHUM AREA (1000 ha)', 'SORGHUM PRODUCTION (1000 tons)','SORGHUM YIELD (Kg per ha)','PEARL MILLET AREA (1000 ha)','PEARL MILLET PRODUCTION (1000 tons)', 'PEARL MILLET YIELD (Kg per ha)','MAIZE AREA (1000 ha)', 'MAIZE PRODUCTION (1000 tons)','MAIZE YIELD (Kg per ha)','FINGER MILLET AREA (1000 ha)','FINGER MILLET PRODUCTION (1000 tons)','FINGER MILLET YIELD (Kg per ha)','BARLEY AREA (1000 ha)','BARLEY PRODUCTION (1000 tons)', 'BARLEY YIELD (Kg per ha)','CHICKPEA AREA (1000 ha)', 'CHICKPEA PRODUCTION (1000 tons)','CHICKPEA YIELD (Kg per ha)','PIGEONPEA AREA (1000 ha)','PIGEONPEA PRODUCTION (1000 tons)', 'PIGEONPEA YIELD (Kg per ha)','MINOR PULSES AREA (1000 ha)', 'MINOR PULSES PRODUCTION (1000 tons)','MINOR PULSES YIELD (Kg per ha)','GROUNDNUT AREA (1000 ha)','GROUNDNUT PRODUCTION (1000 tons)', 'GROUNDNUT YIELD (Kg per ha)','SESAMUM AREA (1000 ha)', 'SESAMUM PRODUCTION (1000 tons)','SESAMUM YIELD (Kg per ha)','RAPESEED AND MUSTARD AREA (1000 ha)','RAPESEED AND MUSTARD PRODUCTION (1000 tons)','RAPESEED AND MUSTARD YIELD (Kg per ha)','CASTOR AREA (1000 ha)', 'CASTOR PRODUCTION (1000 tons)','CASTOR YIELD (Kg per ha)','LINSEED AREA (1000 ha)','LINSEED PRODUCTION (1000 tons)','LINSEED YIELD (Kg per ha)','SUNFLOWER AREA (1000 ha)', 'SUNFLOWER PRODUCTION (1000 tons)','SUNFLOWER YIELD (Kg per ha)','SOYABEAN YIELD (Kg per ha)','OILSEEDS AREA (1000 ha)', 'OILSEEDS PRODUCTION (1000 tons)','OILSEEDS YIELD (Kg per ha)','SUGARCANE AREA (1000 ha)','SUGARCANE PRODUCTION (1000 tons)', 'SUGARCANE YIELD (Kg per ha)','COTTON AREA (1000 ha)', 'COTTON PRODUCTION (1000 tons)','COTTON YIELD (Kg per ha)']  

Q1 = data[cols].quantile(0.25)
Q3 = data[cols].quantile(0.75)
IQR = Q3 - Q1
whisker_width = 1.5
lower_whisker = Q1 -(whisker_width*IQR)
upper_whisker = Q3 + (whisker_width*IQR)
data[cols]=np.where(data[cols]>upper_whisker,upper_whisker,np.where(data[cols]<lower_whisker,lower_whisker,data[cols]))


#Dividing the dataset into 23 according to the crops
data_rice = pd.DataFrame(data[['Dist Code', 'Year', 'State Code', 'State Name','Dist Name', 'RICE AREA (1000 ha)', 'RICE PRODUCTION (1000 tons)','RICE YIELD (Kg per ha)']])
data_wheat = pd.DataFrame(data[['Dist Code', 'Year', 'State Code', 'State Name','Dist Name','WHEAT AREA (1000 ha)','WHEAT PRODUCTION (1000 tons)','WHEAT YIELD (Kg per ha)']])
data_kharif = pd.DataFrame(data[['Dist Code', 'Year', 'State Code', 'State Name','Dist Name','KHARIF SORGHUM AREA (1000 ha)', 'KHARIF SORGHUM PRODUCTION (1000 tons)','KHARIF SORGHUM YIELD (Kg per ha)' ]])
data_rabi = pd.DataFrame(data[['Dist Code', 'Year', 'State Code', 'State Name','Dist Name','RABI SORGHUM AREA (1000 ha)','RABI SORGHUM PRODUCTION (1000 tons)', 'RABI SORGHUM YIELD (Kg per ha)']])
data_sorghum = pd.DataFrame(data[['Dist Code', 'Year', 'State Code', 'State Name','Dist Name','SORGHUM AREA (1000 ha)', 'SORGHUM PRODUCTION (1000 tons)','SORGHUM YIELD (Kg per ha)']])
data_pearl_millet = pd.DataFrame(data[['Dist Code', 'Year', 'State Code', 'State Name','Dist Name','PEARL MILLET AREA (1000 ha)','PEARL MILLET PRODUCTION (1000 tons)', 'PEARL MILLET YIELD (Kg per ha)']])
data_maize = pd.DataFrame(data[['Dist Code', 'Year', 'State Code', 'State Name','Dist Name','MAIZE AREA (1000 ha)', 'MAIZE PRODUCTION (1000 tons)','MAIZE YIELD (Kg per ha)']])
data_finger_millet = pd.DataFrame(data[['Dist Code', 'Year', 'State Code', 'State Name','Dist Name', 'FINGER MILLET AREA (1000 ha)','FINGER MILLET PRODUCTION (1000 tons)','FINGER MILLET YIELD (Kg per ha)']])
data_barley = pd.DataFrame(data[['Dist Code', 'Year', 'State Code', 'State Name','Dist Name','BARLEY AREA (1000 ha)','BARLEY PRODUCTION (1000 tons)', 'BARLEY YIELD (Kg per ha)']])
data_chickpea = pd.DataFrame(data[['Dist Code', 'Year', 'State Code', 'State Name','Dist Name','CHICKPEA AREA (1000 ha)', 'CHICKPEA PRODUCTION (1000 tons)','CHICKPEA YIELD (Kg per ha)']])
data_pigeonpea = pd.DataFrame(data[['Dist Code', 'Year', 'State Code', 'State Name','Dist Name','PIGEONPEA AREA (1000 ha)','PIGEONPEA PRODUCTION (1000 tons)', 'PIGEONPEA YIELD (Kg per ha)']])
data_minor_pulses = pd.DataFrame(data[['Dist Code', 'Year', 'State Code', 'State Name','Dist Name','MINOR PULSES AREA (1000 ha)', 'MINOR PULSES PRODUCTION (1000 tons)','MINOR PULSES YIELD (Kg per ha)']])
data_ground_nut = pd.DataFrame(data[['Dist Code', 'Year', 'State Code', 'State Name','Dist Name','GROUNDNUT AREA (1000 ha)','GROUNDNUT PRODUCTION (1000 tons)', 'GROUNDNUT YIELD (Kg per ha)']])
data_sesamum = pd.DataFrame(data[['Dist Code', 'Year', 'State Code', 'State Name','Dist Name','SESAMUM AREA (1000 ha)', 'SESAMUM PRODUCTION (1000 tons)','SESAMUM YIELD (Kg per ha)']])
data_rapeseed_mustard = pd.DataFrame(data[['Dist Code', 'Year', 'State Code', 'State Name','Dist Name','RAPESEED AND MUSTARD AREA (1000 ha)','RAPESEED AND MUSTARD PRODUCTION (1000 tons)','RAPESEED AND MUSTARD YIELD (Kg per ha)']])
data_safflower = pd.DataFrame(data[['Dist Code', 'Year', 'State Code', 'State Name','Dist Name','SAFFLOWER AREA (1000 ha)','SAFFLOWER PRODUCTION (1000 tons)', 'SAFFLOWER YIELD (Kg per ha)']])
data_castor = pd.DataFrame(data[['Dist Code', 'Year', 'State Code', 'State Name','Dist Name','CASTOR AREA (1000 ha)', 'CASTOR PRODUCTION (1000 tons)','CASTOR YIELD (Kg per ha)']])
data_linseed = pd.DataFrame(data[['Dist Code', 'Year', 'State Code', 'State Name','Dist Name','LINSEED AREA (1000 ha)','LINSEED PRODUCTION (1000 tons)','LINSEED YIELD (Kg per ha)']])
data_sunflower = pd.DataFrame(data[['Dist Code', 'Year', 'State Code', 'State Name','Dist Name','SUNFLOWER AREA (1000 ha)', 'SUNFLOWER PRODUCTION (1000 tons)','SUNFLOWER YIELD (Kg per ha)']])
data_soybean = pd.DataFrame(data[['Dist Code', 'Year', 'State Code', 'State Name','Dist Name','SOYABEAN AREA (1000 ha)','SOYABEAN PRODUCTION (1000 tons)', 'SOYABEAN YIELD (Kg per ha)']])
data_oilseed = pd.DataFrame(data[['Dist Code', 'Year', 'State Code', 'State Name','Dist Name','OILSEEDS AREA (1000 ha)', 'OILSEEDS PRODUCTION (1000 tons)','OILSEEDS YIELD (Kg per ha)']])
data_sugarcane = pd.DataFrame(data[['Dist Code', 'Year', 'State Code', 'State Name','Dist Name','SUGARCANE AREA (1000 ha)','SUGARCANE PRODUCTION (1000 tons)', 'SUGARCANE YIELD (Kg per ha)']])
data_cotton = pd.DataFrame(data[['Dist Code', 'Year', 'State Code', 'State Name','Dist Name','COTTON AREA (1000 ha)', 'COTTON PRODUCTION (1000 tons)','COTTON YIELD (Kg per ha)']])

dfs = [data_rice , data_wheat , data_kharif, data_rabi , data_sorghum , data_pearl_millet, data_maize , data_finger_millet , data_barley , data_chickpea , data_pigeonpea , data_minor_pulses , data_ground_nut , data_sesamum , data_rapeseed_mustard , data_safflower , data_castor , data_linseed , data_sunflower , data_soybean , data_oilseed , data_sugarcane , data_cotton]


#Encoding categorical variables

from sklearn.preprocessing import LabelEncoder
def onehot_encoding(df):
    df1= pd.get_dummies(df['State Name'])
    df = df.drop(['State Name'], axis = 1)
    df = df.merge(df1, left_index=True, right_index=True, how = "left")
    df = pd.DataFrame(df)
    return df

data_rice = onehot_encoding(data_rice)
data_wheat = onehot_encoding(data_wheat)
data_kharif = onehot_encoding(data_kharif)
data_rabi = onehot_encoding(data_rabi)
data_sorghum = onehot_encoding(data_sorghum)
data_pearl_millet = onehot_encoding(data_pearl_millet)
data_maize = onehot_encoding(data_maize)
data_finger_millet = onehot_encoding(data_finger_millet)
data_barley = onehot_encoding(data_barley)
data_chickpea = onehot_encoding(data_chickpea)
data_pigeonpea = onehot_encoding(data_pigeonpea)
data_minor_pulses = onehot_encoding(data_minor_pulses)
data_ground_nut = onehot_encoding(data_ground_nut)
data_sesamum = onehot_encoding(data_sesamum)
data_rapeseed_mustard = onehot_encoding(data_rapeseed_mustard)
data_safflower = onehot_encoding(data_safflower)
data_castor = onehot_encoding(data_castor)
data_linseed = onehot_encoding(data_linseed)
data_sunflower = onehot_encoding(data_sunflower)
data_soybean = onehot_encoding(data_soybean)
data_oilseed = onehot_encoding(data_oilseed)
data_sugarcane = onehot_encoding(data_sugarcane)
data_cotton = onehot_encoding(data_cotton)

In [5]:
data_rice.head()

,Dist Code,Year,State Code,Dist Name,RICE AREA (1000 ha),RICE PRODUCTION (1000 tons),RICE YIELD (Kg per ha),Andhra Pradesh,Assam,Bihar,...,Madhya Pradesh,Maharashtra,Orissa,Punjab,Rajasthan,Tamil Nadu,Telangana,Uttar Pradesh,Uttarakhand,West Bengal
0,1.0,1966,14,Durg,462.875,185.0,337.59,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,1.0,1967,14,Durg,462.875,409.0,747.71,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,1.0,1968,14,Durg,462.875,468.0,841.27,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,1.0,1969,14,Durg,462.875,400.8,711.40,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,1.0,1970,14,Durg,462.875,473.6,828.55,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [6]:
enc = LabelEncoder()
def label_encoding(df):
    df['Dist Name'] = enc.fit_transform(df['Dist Name'])
    return df


data_rice = label_encoding(data_rice)
data_wheat = label_encoding(data_wheat)
data_kharif = label_encoding(data_kharif)
data_rabi = label_encoding(data_rabi)
data_sorghum = label_encoding(data_sorghum)
data_pearl_millet = label_encoding(data_pearl_millet)
data_maize = label_encoding(data_maize)
data_finger_millet = label_encoding(data_finger_millet)
data_barley = label_encoding(data_barley)
data_chickpea = label_encoding(data_chickpea)
data_pigeonpea = label_encoding(data_pigeonpea)
data_minor_pulses = label_encoding(data_minor_pulses)
data_ground_nut = label_encoding(data_ground_nut)
data_sesamum = label_encoding(data_sesamum)
data_rapeseed_mustard = label_encoding(data_rapeseed_mustard)
data_safflower = label_encoding(data_safflower)
data_castor = label_encoding(data_castor)
data_linseed = label_encoding(data_linseed)
data_sunflower = label_encoding(data_sunflower)
data_soybean = label_encoding(data_soybean)
data_oilseed = label_encoding(data_oilseed)
data_sugarcane = label_encoding(data_sugarcane)
data_cotton = label_encoding(data_cotton)

In [7]:
data_rice.head()

,Dist Code,Year,State Code,Dist Name,RICE AREA (1000 ha),RICE PRODUCTION (1000 tons),RICE YIELD (Kg per ha),Andhra Pradesh,Assam,Bihar,...,Madhya Pradesh,Maharashtra,Orissa,Punjab,Rajasthan,Tamil Nadu,Telangana,Uttar Pradesh,Uttarakhand,West Bengal
0,1.0,1966,14,92,462.875,185.0,337.59,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,1.0,1967,14,92,462.875,409.0,747.71,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,1.0,1968,14,92,462.875,468.0,841.27,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,1.0,1969,14,92,462.875,400.8,711.40,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,1.0,1970,14,92,462.875,473.6,828.55,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [8]:
#Feature Reduction

data = data.drop(['VEGETABLES AREA (1000 ha)','FRUITS AND VEGETABLES AREA (1000 ha)', 'POTATOES AREA (1000 ha)', 'ONION AREA (1000 ha)', 'FODDER AREA (1000 ha)' ], axis=1)

#Feature Engineering

def feature_engg(df):
      cols = df.columns
      df['skew'] = df[cols].skew(axis = 1)
      df['kurt'] = df[cols].kurt(axis = 1)
      return df

data_rice = feature_engg(data_rice)
data_wheat = feature_engg(data_wheat)
data_kharif = feature_engg(data_kharif)
data_rabi = feature_engg(data_rabi)
data_sorghum = feature_engg(data_sorghum)
data_pearl_millet = feature_engg(data_pearl_millet)
data_maize = feature_engg(data_maize)
data_finger_millet = feature_engg(data_finger_millet)
data_barley = feature_engg(data_barley)
data_chickpea = feature_engg(data_chickpea)
data_pigeonpea = feature_engg(data_pigeonpea)
data_minor_pulses = feature_engg(data_minor_pulses)
data_ground_nut = feature_engg(data_ground_nut)
data_sesamum = feature_engg(data_sesamum)
data_rapeseed_mustard = feature_engg(data_rapeseed_mustard)
data_safflower = feature_engg(data_safflower)
data_castor = feature_engg(data_castor)
data_linseed = feature_engg(data_linseed)
data_sunflower = feature_engg(data_sunflower)
data_soybean = feature_engg(data_soybean)
data_oilseed = feature_engg(data_oilseed)
data_sugarcane = feature_engg(data_sugarcane)
data_cotton = feature_engg(data_cotton)

In [9]:
data_rice.head()

,Dist Code,Year,State Code,Dist Name,RICE AREA (1000 ha),RICE PRODUCTION (1000 tons),RICE YIELD (Kg per ha),Andhra Pradesh,Assam,Bihar,...,Orissa,Punjab,Rajasthan,Tamil Nadu,Telangana,Uttar Pradesh,Uttarakhand,West Bengal,skew,kurt
0,1.0,1966,14,92,462.875,185.0,337.59,0,0,0,...,0,0,0,0,0,0,0,0,4.581654,22.177591
1,1.0,1967,14,92,462.875,409.0,747.71,0,0,0,...,0,0,0,0,0,0,0,0,3.908785,16.668058
2,1.0,1968,14,92,462.875,468.0,841.27,0,0,0,...,0,0,0,0,0,0,0,0,3.740729,15.232559
3,1.0,1969,14,92,462.875,400.8,711.40,0,0,0,...,0,0,0,0,0,0,0,0,3.964211,17.151343
4,1.0,1970,14,92,462.875,473.6,828.55,0,0,0,...,0,0,0,0,0,0,0,0,3.752605,15.349460

In [10]:
#Scaling the variable 

from sklearn.preprocessing import StandardScaler
scaler=StandardScaler()

def scaling(X):
    X1= X[['Dist Code','Year','State Code', 'Dist Name']]
    X = X.drop(['Dist Code','Year','State Code', 'Dist Name'], axis=1 )
    X = pd.DataFrame(scaler.fit_transform(X),columns=X.columns, index =X.index)
    X = X.merge(X1, left_index=True, right_index=True, how = "left")
    return X


data_rice = scaling(data_rice)
data_wheat = scaling(data_wheat)
data_kharif = scaling(data_kharif)
data_rabi = scaling(data_rabi)
data_sorghum = scaling(data_sorghum)
data_pearl_millet = scaling(data_pearl_millet)
data_maize = scaling(data_maize)
data_finger_millet = scaling(data_finger_millet)
data_barley = scaling(data_barley)
data_chickpea = scaling(data_chickpea)
data_pigeonpea = scaling(data_pigeonpea)
data_minor_pulses = scaling(data_minor_pulses)
data_ground_nut = scaling(data_ground_nut)
data_sesamum = scaling(data_sesamum)
data_rapeseed_mustard = scaling(data_rapeseed_mustard)
data_safflower = scaling(data_safflower)
data_castor = scaling(data_castor)
data_linseed = scaling(data_linseed)
data_sunflower = scaling(data_sunflower)
data_soybean = scaling(data_soybean)
data_oilseed = scaling(data_oilseed)
data_sugarcane = scaling(data_sugarcane)
data_cotton = scaling(data_cotton)

In [11]:
data_rice.head()

,RICE AREA (1000 ha),RICE PRODUCTION (1000 tons),RICE YIELD (Kg per ha),Andhra Pradesh,Assam,Bihar,Chhattisgarh,Gujarat,Haryana,Himachal Pradesh,...,Telangana,Uttar Pradesh,Uttarakhand,West Bengal,skew,kurt,Dist Code,Year,State Code,Dist Name
0,2.498851,-0.056500,-1.213197,-0.191645,-0.182422,-0.191645,7.123903,-0.248069,-0.151869,-0.182422,...,-0.172774,-0.417029,-0.162623,-0.224391,1.296427,1.368642,1.0,1966,14,92
1,2.498851,0.895709,-0.778896,-0.191645,-0.182422,-0.191645,7.123903,-0.248069,-0.151869,-0.182422,...,-0.172774,-0.417029,-0.162623,-0.224391,0.157041,0.327020,1.0,1967,14,92
2,2.498851,1.146514,-0.679820,-0.191645,-0.182422,-0.191645,7.123903,-0.248069,-0.151869,-0.182422,...,-0.172774,-0.417029,-0.162623,-0.224391,-0.127531,0.055627,1.0,1968,14,92
3,2.498851,0.860851,-0.817347,-0.191645,-0.182422,-0.191645,7.123903,-0.248069,-0.151869,-0.182422,...,-0.172774,-0.417029,-0.162623,-0.224391,0.250896,0.418389,1.0,1969,14,92
4,2.498851,1.170319,-0.693290,-0.191645,-0.182422,-0.191645,7.123903,-0.248069,-0.151869,-0.182422,...,-0.172774,-0.417029,-0.162623,-0.224391,-0.107422,0.077728,1.0,1970,14,92

In [12]:
#Data Modeling

#Defining x 
data_rice_x = data_rice.drop(['RICE YIELD (Kg per ha)'],axis = 1)
data_wheat_x = data_wheat.drop(['WHEAT YIELD (Kg per ha)'], axis =1)
data_kharif_x = data_kharif.drop(['KHARIF SORGHUM YIELD (Kg per ha)' ], axis =1)
data_rabi_x = data_rabi.drop(['RABI SORGHUM YIELD (Kg per ha)'], axis=1)
data_sorghum_x = data_sorghum.drop(['SORGHUM YIELD (Kg per ha)'], axis =1)
data_pearl_millet_x = data_pearl_millet.drop(['PEARL MILLET YIELD (Kg per ha)'], axis =1)
data_maize_x = data_maize.drop(['MAIZE YIELD (Kg per ha)'], axis =1)
data_finger_millet_x = data_finger_millet.drop(['FINGER MILLET YIELD (Kg per ha)'], axis =1)
data_barley_x = data_barley.drop(['BARLEY YIELD (Kg per ha)'], axis =1)
data_chickpea_x = data_chickpea.drop(['CHICKPEA YIELD (Kg per ha)'], axis =1)
data_pigeonpea_x = data_pigeonpea.drop(['PIGEONPEA YIELD (Kg per ha)'], axis =1)
data_minor_pulses_x = data_minor_pulses.drop(['MINOR PULSES YIELD (Kg per ha)'], axis=1)
data_ground_nut_x = data_ground_nut.drop(['GROUNDNUT YIELD (Kg per ha)'], axis =1)
data_sesamum_x = data_sesamum.drop(['SESAMUM YIELD (Kg per ha)'], axis = 1)
data_rapeseed_mustard_x = data_rapeseed_mustard.drop(['RAPESEED AND MUSTARD YIELD (Kg per ha)'], axis =1)
data_safflower_x = data_safflower.drop(['SAFFLOWER YIELD (Kg per ha)'], axis =1)
data_castor_x = data_castor.drop(['CASTOR YIELD (Kg per ha)'], axis =1)
data_linseed_x = data_linseed.drop(['LINSEED YIELD (Kg per ha)'], axis =1)
data_sunflower_x = data_sunflower.drop(['SUNFLOWER YIELD (Kg per ha)'], axis =1)
data_soybean_x = data_soybean.drop(['SOYABEAN YIELD (Kg per ha)'], axis =1)
data_oilseed_x = data_oilseed.drop(['OILSEEDS YIELD (Kg per ha)'], axis =1)
data_sugarcane_x = data_sugarcane.drop(['SUGARCANE YIELD (Kg per ha)'], axis = 1)
data_cotton_x = data_cotton.drop(['COTTON YIELD (Kg per ha)'], axis = 1)

#Defining y
data_rice_y = data_rice['RICE YIELD (Kg per ha)']
data_wheat_y = data_wheat['WHEAT YIELD (Kg per ha)']
data_kharif_y = data_kharif['KHARIF SORGHUM YIELD (Kg per ha)']
data_rabi_y = data_rabi['RABI SORGHUM YIELD (Kg per ha)']
data_sorghum_y = data_sorghum['SORGHUM YIELD (Kg per ha)']
data_pearl_millet_y = data_pearl_millet['PEARL MILLET YIELD (Kg per ha)']
data_maize_y = data_maize['MAIZE YIELD (Kg per ha)']
data_finger_millet_y = data_finger_millet['FINGER MILLET YIELD (Kg per ha)']
data_barley_y = data_barley['BARLEY YIELD (Kg per ha)']
data_chickpea_y = data_chickpea['CHICKPEA YIELD (Kg per ha)']
data_pigeonpea_y = data_pigeonpea['PIGEONPEA YIELD (Kg per ha)']
data_minor_pulses_y = data_minor_pulses['MINOR PULSES YIELD (Kg per ha)']
data_ground_nut_y= data_ground_nut['GROUNDNUT YIELD (Kg per ha)']
data_sesamum_y= data_sesamum['SESAMUM YIELD (Kg per ha)']
data_rapeseed_mustard_y = data_rapeseed_mustard['RAPESEED AND MUSTARD YIELD (Kg per ha)']
data_safflower_y = data_safflower['SAFFLOWER YIELD (Kg per ha)']
data_castor_y = data_castor['CASTOR YIELD (Kg per ha)']
data_linseed_y = data_linseed['LINSEED YIELD (Kg per ha)']
data_sunflower_y = data_sunflower['SUNFLOWER YIELD (Kg per ha)']
data_soybean_y = data_soybean['SOYABEAN YIELD (Kg per ha)']
data_oilseed_y = data_oilseed['OILSEEDS YIELD (Kg per ha)']
data_sugarcane_y = data_sugarcane['SUGARCANE YIELD (Kg per ha)']
data_cotton_y = data_cotton['COTTON YIELD (Kg per ha)']

In [13]:
data_rice.head()

,RICE AREA (1000 ha),RICE PRODUCTION (1000 tons),RICE YIELD (Kg per ha),Andhra Pradesh,Assam,Bihar,Chhattisgarh,Gujarat,Haryana,Himachal Pradesh,...,Telangana,Uttar Pradesh,Uttarakhand,West Bengal,skew,kurt,Dist Code,Year,State Code,Dist Name
0,2.498851,-0.056500,-1.213197,-0.191645,-0.182422,-0.191645,7.123903,-0.248069,-0.151869,-0.182422,...,-0.172774,-0.417029,-0.162623,-0.224391,1.296427,1.368642,1.0,1966,14,92
1,2.498851,0.895709,-0.778896,-0.191645,-0.182422,-0.191645,7.123903,-0.248069,-0.151869,-0.182422,...,-0.172774,-0.417029,-0.162623,-0.224391,0.157041,0.327020,1.0,1967,14,92
2,2.498851,1.146514,-0.679820,-0.191645,-0.182422,-0.191645,7.123903,-0.248069,-0.151869,-0.182422,...,-0.172774,-0.417029,-0.162623,-0.224391,-0.127531,0.055627,1.0,1968,14,92
3,2.498851,0.860851,-0.817347,-0.191645,-0.182422,-0.191645,7.123903,-0.248069,-0.151869,-0.182422,...,-0.172774,-0.417029,-0.162623,-0.224391,0.250896,0.418389,1.0,1969,14,92
4,2.498851,1.170319,-0.693290,-0.191645,-0.182422,-0.191645,7.123903,-0.248069,-0.151869,-0.182422,...,-0.172774,-0.417029,-0.162623,-0.224391,-0.107422,0.077728,1.0,1970,14,92

In [14]:
dfs = [ (data_rice_x , data_rice_y ) , (data_wheat_x , data_wheat_y) , (data_kharif_x,data_kharif_y),(data_rabi_x,data_rabi_y) , (data_sorghum_x,data_sorghum_y) , (data_pearl_millet_x,data_pearl_millet_y) , (data_maize_x,data_maize_y) , (data_finger_millet_x,data_finger_millet_y) , (data_barley_x,data_barley_y) , (data_chickpea_x,data_chickpea_y) , (data_pigeonpea_x,data_pigeonpea_y)  , (data_minor_pulses_x,data_minor_pulses_y) , (data_ground_nut_x,data_ground_nut_y)  , (data_sesamum_x,data_sesamum_y) , (data_rapeseed_mustard_x,data_rapeseed_mustard_y) , (data_safflower_x,data_safflower_y) , (data_castor_x,data_castor_y) , (data_linseed_x,data_linseed_y) , (data_sunflower_x,data_sunflower_y) , (data_soybean_x,data_soybean_y) , (data_oilseed_x,data_oilseed_y) , (data_sugarcane_x,data_sugarcane_y) , (data_cotton_x,data_cotton_y) ]

In [15]:
from sklearn.model_selection import train_test_split
from sklearn import linear_model
from sklearn.metrics import mean_squared_error
from sklearn.metrics import mean_absolute_error
from sklearn.ensemble import RandomForestRegressor
from sklearn.svm import SVR
from sklearn.linear_model import Lasso
from sklearn.metrics import r2_score

In [16]:
def TrainandTestwithAlgorithm(X,y,algorithm,modelname):
    
    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)
    
    model = algorithm
    model.fit(X_train, y_train)

    prediction = model.predict(X_test)
    print('MSE is: ',mean_squared_error(y_test,prediction))
    print('MAE is: ',mean_absolute_error(y_test,prediction))
    print('R-squared is: ',r2_score(y_test,prediction))
    model = {}
    
    model['Algorithm'] = modelname
    model['MSE'] = mean_squared_error(y_test,prediction)
    model['MAE'] = mean_absolute_error(y_test,prediction)
    model['R2'] = r2_score(y_test,prediction)
    
    return model

In [17]:
DataModels = pd.DataFrame()

algorithms = {"Random Forest": RandomForestRegressor(),"Linear Regression": linear_model.LinearRegression(),"Lasso": Lasso(alpha=0.001),
              "Support Vector Regression": SVR(C=8,epsilon=0.2,gamma=0.5)}

In [ ]:
for i in dfs:
  obj1,obj2=i
  for i,j in algorithms.items():
    print("Algorithm Performance: {}".format(i))    
    model = TrainandTestwithAlgorithm(obj1,obj2,j,i)
    DataModels = DataModels.append(model,ignore_index=True)    
    print()  
    DataModels.sort_values(by='MSE',ascending=False)

Algorithm Performance: Random Forest
MSE is:  0.024966922888828305
MAE is:  0.06195690479961289
R-squared is:  0.9747627998732441

Algorithm Performance: Linear Regression
MSE is:  0.18027552998849178
MAE is:  0.29549627217422797
R-squared is:  0.8215537331094384

Algorithm Performance: Lasso

D:\Anaconda\lib\site-packages\sklearn\linear_model\_coordinate_descent.py:647: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.236e+02, tolerance: 1.299e+00
  model = cd_fast.enet_coordinate_descent(

MSE is:  0.18101833369073764
MAE is:  0.3003186522318146
R-squared is:  0.8148099412724358

Algorithm Performance: Support Vector Regression
MSE is:  0.2773752131828087
MAE is:  0.4137944046245022
R-squared is:  0.7231094345268175

Algorithm Performance: Random Forest
MSE is:  0.016798481742438795
MAE is:  0.044417914916116366
R-squared is:  0.9832514279559698

Algorithm Performance: Linear Regression
MSE is:  0.12717944535341935
MAE is:  0.25677532460323305
R-squared is:  0.8742724682111431

Algorithm Performance: Lasso
MSE is:  0.12618508686957242
MAE is:  0.2518542628314142
R-squared is:  0.874298996451559

Algorithm Performance: Support Vector Regression
MSE is:  0.2502113645087896
MAE is:  0.3906876712965661
R-squared is:  0.7524518705335667

Algorithm Performance: Random Forest
MSE is:  0.005949564521523781
MAE is:  0.018804079568050497
R-squared is:  0.9941449189647094

Algorithm Performance: Linear Regression
MSE is:  0.04415733953973403
MAE is:  0.1341174113615958
R-squared is:  0.9569191752256732

Algorithm Performance: Lasso
MSE is:  0.04374564654443479
MAE is:  0.13388586133315517
R-squared is:  0.9573503824747965

Algorithm Performance: Support Vector Regression
MSE is:  0.32876526818139956
MAE is:  0.4305800670167363
R-squared is:  0.6657913144659966

Algorithm Performance: Random Forest
MSE is:  0.1218992691042188
MAE is:  0.054680730752787635
R-squared is:  0.873081616512088

Algorithm Performance: Linear Regression
MSE is:  0.4585574944102295
MAE is:  0.1471916967821032
R-squared is:  0.6019232443386502

Algorithm Performance: Lasso
MSE is:  0.4191815853912409
MAE is:  0.14953869169850156
R-squared is:  0.6327890442342206

Algorithm Performance: Support Vector Regression
MSE is:  0.44340098177749343
MAE is:  0.3821325266791862
R-squared is:  0.5123787791709203

Algorithm Performance: Random Forest
MSE is:  0.003211991362693303
MAE is:  0.014278668801665133
R-squared is:  0.9966683670855806

Algorithm Performance: Linear Regression
MSE is:  0.04000047584449834
MAE is:  0.13110990929912836
R-squared is:  0.9605509441431921

Algorithm Performance: Lasso
MSE is:  0.03994119599621113
MAE is:  0.13221522353006712
R-squared is:  0.9606197442023815

Algorithm Performance: Support Vector Regression
MSE is:  0.3168348704095028
MAE is:  0.4140305963950153
R-squared is:  0.6822381812316144

Algorithm Performance: Random Forest
MSE is:  0.0014558673922328428
MAE is:  0.010977707680680572
R-squared is:  0.9985315654133873

Algorithm Performance: Linear Regression
MSE is:  0.032945748348698595
MAE is:  0.12821873553220167
R-squared is:  0.9648829233359825

Algorithm Performance: Lasso
MSE is:  0.034732756074665076
MAE is:  0.13124866371433005
R-squared is:  0.9654029125640651

Algorithm Performance: Support Vector Regression
MSE is:  0.29727099660641587
MAE is:  0.4145442842389793
R-squared is:  0.7083407905241246

Algorithm Performance: Random Forest
MSE is:  0.05076562482076742
MAE is:  0.08134956860517381
R-squared is:  0.9490113970252074

Algorithm Performance: Linear Regression
MSE is:  0.2519177357921642
MAE is:  0.35132335888167227
R-squared is:  0.7473480913302312

Algorithm Performance: Lasso
MSE is:  0.24962230880898584
MAE is:  0.3500091597378605
R-squared is:  0.7425917790497353

Algorithm Performance: Support Vector Regression
MSE is:  0.3481463459510997
MAE is:  0.44846822560534044
R-squared is:  0.6583442716140182

Algorithm Performance: Random Forest
MSE is:  0.00015702872565160543
MAE is:  0.004427528930910384
R-squared is:  0.9998344596007264

Algorithm Performance: Linear Regression
MSE is:  0.008978563622000054
MAE is:  0.0638297993513227
R-squared is:  0.9909541808205874

Algorithm Performance: Lasso
MSE is:  0.009077005459673297
MAE is:  0.06458301323985718
R-squared is:  0.9907952229804913

Algorithm Performance: Support Vector Regression
MSE is:  0.25858439438781117
MAE is:  0.41026982867114564
R-squared is:  0.7456490916755619

Algorithm Performance: Random Forest
MSE is:  0.01672247786668589
MAE is:  0.033810311940788124
R-squared is:  0.9831209230666916

Algorithm Performance: Linear Regression
MSE is:  0.11382427553572765
MAE is:  0.21842415017235928
R-squared is:  0.884458794715578

Algorithm Performance: Lasso
MSE is:  0.11980449419780877
MAE is:  0.22518946116277253
R-squared is:  0.8799717444325911

Algorithm Performance: Support Vector Regression
MSE is:  0.24563509882566217
MAE is:  0.38824580372092404
R-squared is:  0.7610984169505889

Algorithm Performance: Random Forest
MSE is:  0.0002865367649929297
MAE is:  0.00958359642515208
R-squared is:  0.9997048722966441

Algorithm Performance: Linear Regression
MSE is:  0.017028031939244504
MAE is:  0.09981425412029904
R-squared is:  0.9824609715941603

Algorithm Performance: Lasso
MSE is:  0.019143012461680733
MAE is:  0.10704147932611738
R-squared is:  0.9810284795397037

Algorithm Performance: Support Vector Regression